version: "3.8"
services:
  wp-db:
    image: "postgres"
    container_name: "wp-2024-eshop"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=e-shop

    ports:
      - "5433:5432"